# SPDX-FileCopyrightText: 2022 Michael Jeanson <mjeanson@efficios.com>
#
# SPDX-License-Identifier: MIT

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envmap
data:
  LTTNG_HOME: "/lttng"
  LTTNG_UST_DEBUG: "1"
